export interface product {
    CODPRD: string;
    NOMEFANTASIA: string;
    CODBARRAS : string;
    PRATELEIRA: string;
    DESC_CURVA: string;
    DESC_GRUPO: string;
    DESC_FABRICANTE: string;
    CODGRUPO: string;
    PRECO1: number;
    PRECO2: number;
    PRECO?: number;
    precos_filial?: {
        CODEMPRESA: number;
        CODFILIAL: number;
        PRECO: number;
        CUSTOUNITARIO: number;
        CUSTOMEDIO: number;
        CUSTOREPOSICAOA: number;
        CUSTOREPOSICAOB: number;
        MARGEMLUCRO: number;
        ESTOQUEMINIMO: number;
        ESTOQUEMAXIMO: number;
        PONTOPEDIDO: number;
        DTULTIMAVENDA: string | null;
        DTULTIMACOMPRA: string | null;
        ULTPRECOCOMPRA: number;
        QTDULTIMACOMPRA: number;
        NUMDOCULTCOMPRA: string | null;
        ULTPRECOVENDA: number;
    }[];
    PONTOEQ: number;
    CUSTOUNITARIO: number;
    CUSTOMEDIO: number;
    CUSTOSVARIAVEIS: number;
    SALDOGERALFISICO: number;
    SALDOGERALFISICO2: number;
    CODSIT: string;
    CODDEPARTAMENTO: string;
    DEPOSITO: string;
    UNIDADE: string;
    CODUNDVENDA: string;
    CD_LEGENDA: number;
}
